chart10/UniRoute

.env, api/api.py
I added the configuration needed to allow flask code to read and write info to the MySQL database I'm hosting on my machine. Next step is to make sure everyone has the right credentials to use it
=> Database flask branch

api/api.py, api/tempCodeRunnerFile.py, src/App.js, src/components/pages/Register.js, src/components/pages/apiRegister.js
I added some code to the '/signup' route in api.py that check if the submitted username is already in the 'users' table of the database. If it is, the route returns 'There is already an account with that username.' Otherwise the registration form is entered into the table as a new row. Still left to do is pass that message up to React and present it to the user. Right now it just prints to the Flask backend console.
I also simplified my code for the registration path a bit in Registration.js.
=> Registration path now prevents duplicate entry into 'users' table of DB

api/api.py, api/googleroutes.py, src/App.js, src/components/UseToken.js, src/components/pages/Login.js
A few things:
1. Refactored login, to use axios and match up with jwt-Authentication in flask
2. created useToken to handle the jwt authentication token 
3. in backend, implemented jwt-authentication for logging in (/token) and jwt refresh so the individual is not logged out. 
4. signup route was renamed to register
5. deleted some unnecissary code.
=> Dugan main

src/App.js, src/components/Map.js, src/components/pages/Getroute.js, src/index.js
It's all coming together! Using the input form on the GetRoute.js page you can now specify the origin, destination and travel mode of a route, and on clicking submit the route will render dynamically. This is still an API call made by the front end Map Javascript API, rather than the back end Directions API via Flask, but progress is progress. I'll continue to tinker with the back end API call and see if we can get it working with the same fidelity, either this week or next sprint. Or better yet, maybe one of you guys could take a crack at it for Sprint 5.
Here's what a route looks like when you hit submit.
I'm still a little shaky on how the React Router Dom works, but I managed to create all the needed useStates to allow GetRoute.js to send it's information to Map.js. In Index.js there …
=> GetRoute.js input fields work + directions panel renders properly

markdowns/database.md, public/index.html, src/components/Navbar.css, src/components/Navbar.js, src/index.js
This is just  a couple of minor changes.
1. I've imported the Rubik Mono One font we used for our wire frame. It's a link tag in the head of the index.html file in the public folder. That should make the font usable from any CSS file inside src. Right now I'm only using it for the UniRoute logo, but we can probably use it in other places too.
2. I changed the title of Getroute.js to GetRoute.js because it was bugging me every time I looked at it. I believe I've updated that everywhere in the code. If a page link isn't working, let me know. This might be why.
3. Last I added a couple of lines to the code snippet in database.md. I added "USE UniRouteDB;" right before the table declarations to make sure that the code runs properly if you copy/paste. I also made it so the "password" attribute …
=> Rubik font, Getroute.js changed to GetRoute.js, updated database.md

api/api.py, public/index.html, src/components/Map.js, src/components/Navbar.css, src/components/Navbar.js, src/components/pages/AddressList.js, src/components/pages/Getroute.js, src/components/pages/Login.js, src/components/pages/Profile.js, src/components/pages/pages.css, src/index.js
The "Address Book" section of Profile.js now displays a list of addresses saved to the user's account in the database.
I also updated the font family. 'Rubik' is now available throughout the app through CSS styling. It has three weights, regular 300 for plain old text, bold 500 for important text, and extra bold 900 for titles.
=> User's saved address appear on Profile page + Font update

src/components/Logout.js, src/components/Navbar.js, src/components/pages/pages.css
So, I created a temporary fix to our Navbar functionality. In our web-application our Navbar will respond each time the user logs in and logs out. Its a temporary bandage but we met 1 of our small core MVP that can be improved. I spoke with Batya and she recommended us to look into Recoil react as an easier alternative. Then when the user logs out it will refresh the whole page.
=> navbar functionality

README.md, src/components/Map.js, src/components/pages/GetRoute.js
I've updated the code in 3 ways:
1) The addressData useState now makes a back end call on GetRoute.js which makes addressData available whenever a route is being made. Kind of a quick fix until we figure out if there's a better way to make user data available app-wide.
2) I messed around with the step-by-step panel in the directionsRenderer in Map.js and figured out what to do. The problem is that directionsRenderer is populating the panel data BEFORE the panel is rendered. Thus it will appear blank on the first route, but each subsequent route would show up fine. If we make it a div on the map that always exists outside of whether directionsRenderer is processing directions then it will always be able to interact with the panel properly. Next I used CSS to hide it with "display: none" …
=> Fixed the panel render bug + input dropdown logic

src/components/Map.js, src/components/pages/GetRoute.js
Just a quick update addressing the changes that Batya suggested for our code. I removed some unused functions from GetRoute.js and Map.js, and I added flask-jwt-extended to our requirementsFlask.txt.
=> remvoed legacy-provider from package.json

src/components/Logout.js, src/components/Navbar.js
Our Navbar displays Log in and Register if the user hasn't logged in. After the user logs in then the user can see their profile and logout on the navbar and hides log in and register. Also our logout button works and also made some changes in our icons to the Login icon and Logout icon as well.
=> navbar update

api/googleroutes.py, src/components/pages/Profile.js, src/components/pages/Register.js, src/components/pages/Schedule.js
This feature is still a work in progress, but there are now functional input fields for customizing a profile specific route for a particular day of the week and time of day. Right now they do not send data to the back end, but if you look at the console you'll see that all the necessary values can be saved. Happy to hear some feedback from you guys.
=> Schedule Route input fields available on Profile page

src/components/Logout.js
Deleted unnecessary code that was originally made to serve as a temporary bandage till our navbar is up and running. Now it just uses that line. I ran a few test and it works properly.
=> Eslinted Logout

api/api.py, markdowns/database.md, src/components/pages/AddressList.js, src/components/pages/Schedule.js
The input fields in the Profile page under Weekly Schedule are now fully functional. Saved directions will be entered into the scheduledRoute table in the database. I had to play with the schema a little bit to make things work, but it's all for the better (and I noted all my changes in database.md). Displaying saved routes later on should be pretty straight forward with the information saved.
So to make the weekday scheduling work I am saving a 7 items long array of boolean values for each saved route, called dayOfWeek. If a boolean is True then that route should be associated with that day. If it's False then it will not be associated with that day. So a route that should show up on a user's weekly planner Monday through Friday will have this array: [true, true, true, true, true, false, …
=> User can save Scheduled Directions to Database

api/api.py, api/apitest.py
Added the backend server unit tests for /token and /register routes. It tests when a user is registered then deletes said user. Also tests for a valid sign it and an invalid sign in.
=> Backend server tests for /token and /register are complete!

api/api.py, src/components/pages/AddressList.js, src/components/pages/GetRoute.js, src/components/pages/Schedule.js, src/components/pages/ScheduleList.js, src/components/pages/pages.css
I've updated the code for both AddressList.js and ScheduleList.js. Each displayed item now has a fully functional "remove" button that will completely remove that item from the database when clicked. There's one hiccup: for the schedule, once a route is removed it does not instantly refresh the whole schedule. Only the item clicked gets removed even though the particular route might appear on several different days. Note that is DOES get removed from all days in the database, but the profile page does not show this until the page is refreshed. Need to figure out how to rearrange the scheduledDirections useState in order to have the schedule fully update when the remove button is clicked.
Second, I toyed around a bit with the CSS to make the schedule display horizontally. Each weekday …
=> Addresses/Scheduled Routes removable + Schedule displays horizontally

src/components/pages/Login.js, src/components/pages/Register.js, src/components/pages/pages.css
I created a better design for our login and register form. When the user clicks the login link on the navbar an overlay will pop up in the center of the screen. Gave it a transparent grey screen background so the user can be focused on the form. The functionality of the x button allows you to exit the overlay and added a few hover effects.
=> css Login/Register

src/components/pages/ScheduleList.js, src/components/pages/ScheduledRoute.js
I took some time this morning to clean up my code for the ScheduleList. Previously I had hard coded the JSX output for every day of the week. It was a mess and there was a lot of repeated code.
I took the repeated JSX and moved it to a new component that represents the output for each day. Now, the ScheduleList JSX runs a for loop over a static array of days of the week and outputs one component for each day in in the array. Now the ScheduleList component is much cleaner and hopefully easier to read. Let me know if this helps. 
There are probably a couple of other places where my code could stand to be refactored a bit for cleanliness and readability. Hit me up if you have suggestions!
=> ScheduleList Refactored

src/components/pages/GetRoute.js, src/components/pages/Schedule.js, src/components/pages/ScheduleList.js, src/components/pages/ScheduledRoute.js
Now, when you click a route in the Weekly Schedule section of the Profile page it will generate a route on the Map immediately. Cool stuff
=> Scheduled Routes now clickable

api/api.py, src/components/Navbar.js, src/components/pages/EditProfile.js, src/components/pages/Profile.js, src/components/pages/editProfile.css
This has all of the edit profile functionality. Now this is implemented with older profile page, but it should be very easy to add  it to the new one. all you'll have to do is edit profile.js and add the button. Also add the two handleprofile functions to make sure that it opens and closes
=> C dugan main

api/api.py, src/components/Navbar.css, src/components/pages/GetRoute.css, src/components/pages/pages.css
Made touchups on our page make it more eye appealing to the user.
=> styling touches
